config/routes.rb
DempApp::Application.routes.draw do

  

  get "books/new"
  get "books/show"
  get "professors/new"
  resources :users
  resources :books
  resources  :professors
  resources :copies , only: [:create, :destroy,:new]
  resources :ratings, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match 'createOrder', to: 'copies#orderCopy',  via: 'post'
  
  match '/metadata', to: 'books#new', via: 'get' 
  

  

end

app/models/professor.rb
class Professor < ActiveRecord::Base

  has_many :ratings, dependent: :destroy

#include Tire::Model::Search
#include Tire::Model::Callbacks
  def self.search(search)
    if search
      find(:all, :conditions => ['firstname LIKE ? OR lastname LIKE ? OR department LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end

  #validates_associated: ratings




end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  
  def new
    @professor=Professor.new
  end
  

 	
  def create
    @professor=Professor.new(professor_params)
    if @professor.save
      flash[:success] = "Professor saved successfuly"
      redirect_to professors_path # used to be new_professor_path
    else
      render 'new'
    end	

  end 

  def index
    if params[:search].present?
      @professors = Professor.search(params[:search])
    else
      @professors = Professor.all
    end
  end


  

  def show
    @professor=Professor.find(params[:id])
    @ratings = @professor.ratings.paginate(page: params[:page]) # this is new
    @rating = @professor.ratings.build

  end
  

  private

    def professor_params
      params.require(:professor).permit(:firstname, :lastname, :department)
    end
      

end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/index.html.erb
<h1>Rate Professor</h1>

<%= form_tag professors_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>




<%= link_to "Add Professor!", professors_new_path, class: "btn btn-large btn-primary" %>

<table>
<th>First Name</th><th>Last Name</th><th>Department</th><th>Rated</th>
<% @professors.each do |p| %>
  <tr><td><%=p.firstname%></td><td><%=p.lastname%></td><td><%=p.department%></td><td>
        <% if Rating.where("professor_id = ?", p.id).count > 0 %>
          <%= Rating.where("professor_id = ?", p.id).average(:value).to_f %>/5
        <% else %>
          NA
        <% end %>
      </td>
      <td><%= link_to "View", p, class: "btn" %></td></tr>


<% end %>

</table>

app/views/professors/match.html.erb
<h1>Rate Professor</h1>
<%= form_tag professors_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search], :id =>'searchfields' %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<ol>
  <% @matchProfessor.each do |p|%>
  <li><%=p.firstname%></li>
  <%end%>
</ol>

app/views/professors/new.html.erb
<h1>Enter New Professor</h1>



<div class="row">
  <div class="span6 offset3">
    <%= form_for(@professor) do |f| %>

      <%= f.label :firstname, "First Name" %>
      <%= f.text_field :firstname %>

      <%= f.label :lastname, "Last Name"%>
      <%= f.text_field :lastname%>

      <%= f.label :department, "Department" %>
      <%= f.text_field :department %>

      
      


      
      <%= f.submit "Save New Professor", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/professors/show.html.erb
<h1>Professor <%= @professor.firstname %> <%= @professor.lastname %> </h1>



<h3>Rated: 
  <% if Rating.where("professor_id = ?", @professor.id).count > 0 %>
    (<%= Rating.where("professor_id = ?", @professor.id).average(:value).to_f %>/5) </h3>
  <% else %>
    Not yet rated</h3>
  <% end %>

<h3>Ratings</h3>

<% @professor.ratings.each do |rating| %>
  <% unless rating.value.nil? %>
    <p>Rating:

<% for i in 1..5 %>
  <% if rating.value >= i %>
    <img src="/assets/star-on-big.png">
  <% else %>
    <img src="/assets/star-off-big.png">
  <% end %>
<% end %>

</p>
    <p>Comment: <%= rating.comment %></p>
    <hr>
  <% end %>
<% end %>
<script>
alert "something";
</script>

<%= render 'shared/ratings_form' %>