config/routes.rb
DempApp::Application.routes.draw do

  

  get "books/new"
  get "books/show"
  get "professors/new"
  resources :users
  resources :books
  resources  :professors
  resources :copies , only: [:create, :destroy,:new]
  resources :ratings, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match 'createOrder', to: 'copies#orderCopy',  via: 'post'
  
  match '/metadata', to: 'books#new', via: 'get' 
  

  

end

app/models/book.rb
require 'matrix'
class Book < ActiveRecord::Base
  has_many :copies, dependent: :destroy
  attr_accessor :vector
 # serialize :book_vector

  after_find do |book|

    if book.book_vector?
      book.vector = YAML::load(book.book_vector)
    else
      arr = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
      book.vector = Vector.elements(arr, copy = true)
    end
  end
  accepts_nested_attributes_for  :copies
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ? OR author LIKE ? OR isbn LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end


end

app/controllers/books_controller.rb
require 'googlebooks'

class BooksController < ApplicationController
  before_action :signed_in_user, only: [:create, :new]
def index
  params[:search].present? ? @books = Book.search(params[:search]) : @books = Book.all
  #@books = Book.all
end
def new
  @book=Book.new

  name = params[:search]
  books = GoogleBooks.search("isbn: #{name}")
  first_book = books.first
   
  if !first_book.nil?
   @title = first_book.title
   @author = first_book.authors
   @isbn = first_book.isbn_13
   @publisher = first_book.publisher
   @date = first_book.published_date
   @pages = first_book.page_count.to_s
   @cover = first_book.image_link(:zoom => 1)
  else 
   @message = "empty"
  end
end

def create
  logger.debug book_params
  book_params.inspect
  @book=Book.new(book_params)
#  @copy=Copy.new #dummy copy
  if @book.save
    flash[:success] = "Book saved successfully"
    params.inspect
#    myparams=copy_params()
    myparams={price: params[:price].values[0], condition: params[:condition].values[0], seller: params[:seller].values[0], user_id: current_user.id}
    logger.debug "========================================="
    logger.debug myparams
    logger.debug "========================================="
    @book.copies.build myparams
    @book.save
    redirect_to @book
  else
    render 'new'
  end

end
def copy_params
    params.require(:copy).permit( :price, :condition, :book_id,:seller)
  end
def show
@book=Book.find(params[:id])
@copies = @book.copies.paginate(page: params[:page])
@copy=@book.copies.build
end

private

def book_params
  params.require(:book).permit(:title, :edition, :author,:isbn)
end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1>Post/Search for a book</h1>

<%= form_tag books_path, method: :get do %>
    <p>
      <%= text_field_tag :search, params[:search],  placeholder: "Search for a book to buy or post..." %>
      <%= submit_tag "Search", name: nil %>
    </p>
<% end %>

<% if @books.empty?%>
<h4>Could not find: "<%= params[:search]%>" in our database</h4>
<h5>Be the first to add this book</h5>
  <%= link_to "Add new book!", books_new_path, class: "btn btn-large btn-primary" %>
<% else %>



<table >
  <tr><th>Title</th><th>Edition</th><th>Author</th><th>ISBN</th><th>Available Copies</th></tr>
  <% @books.each do |b| %>
      <tr><td><%=b.title%></td><td><%=b.edition%></td><td><%=b.author%></td><td><%=b.isbn%></td><td><%= Copy.where("book_id = ? AND sold = ?", b.id, false).count %></td>
      <td><%= link_to "View", b, class: "btn" %></td></tr>

<%end%>
  <% end %>

</table>

app/views/books/new.html.erb
<h1>Enter New Book</h1>

 <%= form_tag metadata_path, method: :get do %>
    <p>
      <%= text_field_tag :search, params[:search],  placeholder:"Enter ISBN and click autocomplete... or enter information manually" %>
      <%= submit_tag "Autocomplete", name: nil %>
      <%= submit_tag "Enter Manually", name:'manually' %>
    </p>
 <% end %>


<% if params[:search].present? %>
 <% if (params[:search]==@isbn) && (!@message.present?) %>
  <%= image_tag(@cover, :alt=> "No cover available", :align=> 'right') %>

  <div class="row">
    <div class="span6 offset3">
      <%= form_for(@book) do |f| %>

        <%= f.label :title, "Title" %>
        <%= f.text_field :title, :value=> @title %>

        <%= f.label :edition, "Edition"%>
        <%= f.text_field :edition, placeholder: "Please Enter the edition..." %>

        <%= f.label :author, "Author" %>
        <%= f.text_field :author, :value=> @author %>

        <%= f.label :isbn, "ISBN" %>
        <%= f.text_field :isbn, :value=> @isbn %>

	<%= label :price, "Price..." %>
	<%= text_field :price, label: "Price...", "size" => 10 %>
	<%= label :condition, "Condition..." %>
	<%= text_field :condition, placeholder: "Condition...", "size" => 50 %>
	<%= label :seller, "How to contact you..." %>
	<%= text_field :seller, placeholder: "How to contact you...", "size" => 50 %>

        <%= f.submit "Save New Book", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
 <% else %>
  <p>Please enter a valid ISBN</p>
 <% end %>
<% end %>


<% if params[:manually] %>
 <div class="row">
    <div class="span6 offset3">
      <%= form_for(@book) do |f| %>

        <%= f.label :title, "Title" %>
        <%= f.text_field :title %>

        <%= f.label :edition, "Edition"%>
        <%= f.text_field :edition %>

        <%= f.label :author, "Author" %>
        <%= f.text_field :author %>

        <%= f.label :isbn, "ISBN" %>
        <%= f.text_field :isbn %>

	<%= label :price, "Price..." %>
	<%= text_field :price, label: "Price...", "size" => 10 %>
	<%= label :condition, "Condition..." %>
	<%= text_field :condition, placeholder: "Condition...", "size" => 50 %>
	<%= label :seller, "How to contact you..." %>
	<%= text_field :seller, placeholder: "How to contact you...", "size" => 50 %>

        <%= f.submit "Save New Book", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<p> Title: <%=  @book.title%><br> Edition: <%=@book.edition%><br>Author:<%= @book.author%><br>ISBN:<%= @book.isbn %></h1></p>
<%= render 'shared/copies_form' %>


  <% if @book.copies.any? %>
      <h3>(<%= @book.copies.count %>)Offers</h3>
      <p>Prices: $<%= @copies.minimum(:price).to_f %> - $<%= @copies.maximum(:price).to_f %></p>
      <p>Average Price: $<%= @copies.average(:price).to_f %></p>
    <table>
      <th>Price</th><th>Condition</th><th>Seller</th><th></th>
      <% @copies.all.sort_by { |c| c.price }.each do |c| %>
        <% unless c.sold %>
          <tr><td>$<%=c.price%></td><td><%=c.condition%></td><td><%= mail_to c.seller%></td>
          <td><% if signed_in? %>

          <% end %></td>

          <td><span class="timestamp">Posted <%= time_ago_in_words(c.created_at) %> ago.</span></td>
          </tr>
        <% end %>
      <% end %>

    </table>

  <% end %>
<%= will_paginate @copies %>